---
version: "2.1"
services:
  writefreely:
    image: nicholaswilde/writefreely:0.13.1-ls1
    container_name: writefreely-default
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - 8080:8080
    volumes:
      - app:/app
      - config:/config
      - defaults:/defaults
volumes:
  app:
  config:
  defaults:
